Repository sethshivam11/campus-space, pull requests merged in 2024-06, with the labels that each got.

#26 Making the navbar sticky and enhancing the navbar with blur
  client/src/components/Navbar.tsx
Labels: enhancement, gssoc, level1

#27 Updated navbar
  client/src/components/Navbar.tsx
Labels: enhancement, gssoc, level1

#28 [enhancement]: added a new controller to update room details
  server/src/controllers/room.controller.ts
  server/src/routes/room.route.ts
Labels: enhancement, gssoc, level2

#38 Added Contribution.md file
  CONTRIBUTION.md
  README.md
Labels: documentation, gssoc, level1

#35 Create pull-request.md
  pull-request.md
Labels: documentation, gssoc, level1

#36 Create contributing.md
  contributing.md
Labels: documentation, enhancement, gssoc, level1

#41 Updated the twitter icon
  client/src/components/Footer.tsx
Labels: enhancement, gssoc, level1

#43 Added issue templates for bug reports and feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, gssoc, level1

#47 Created Learn.md
  Learn.md
Labels: enhancement, gssoc, level1

#57 Update README.md => Added Contributors section
  README.md
Labels: documentation, gssoc, level1
